stages:
  batch_data_preprocessing:
    cmd: python data_import_and_preprocessing/batch_data_preprocessing.py
    deps:
    - data_import_and_preprocessing/batch_data_preprocessing.py
    outs:
    - data/preprocessed
  train_model:
    cmd: python training/model_training.py
    deps:
      - data/preprocessed
      - data_import_and_preprocessing/dataset_formation.py
      - training/model_training.py
      - models/lenet5.py
    params:
      - training.loss
      - training.no_epochs
      - training.batch_size
    outs:
      - training/model/trained_model.h5
      - cache/ds_test.tf
      - cache/additional_info.yaml
  compose_report:
    cmd: python report/report.py
    deps:
      - report/report.py
      - training/model/trained_model.h5
      - cache/ds_test.tf
      - cache/additional_info.yaml
    metrics:
      - metrics.json:
          cache: false