stages:
  dvc-pull:
    cmd: dvc pull
  train:
    cmd: python ./src/training.py
    deps:
      - ./src/model.py
      - ./src/read_and_preprocess_data.py
      - ./src/training.py
    metrics:
      - ./report.json:
          cache: false