path_dataset: /home/lwecke/Datensätze/Datensatz_v1_50p_3reg/Datensatz_v1_50p_3reg/dataset_2023-07-18-exp01
dest_path_preprocessed: /home/lwecke/Datensätze/Datensatz_v1_50p_3reg/Datensatz_v1_50p_3reg/yaw_0.918367326259613
output_path_dataset_training: /home/lwecke/Datensätze/Datensatz_v1_50p_3reg
#path_dataset: /mnt/0A60B2CB60B2BD2F/Projects/flow_regime_recognition_CameraPosition/datasets_preprocessed/Right200
#path_dataset: /mnt/0A60B2CB60B2BD2F/Projects/flow_regime_recognition_CameraPosition/datasets_preprocessed/Front200
path_SdCardPicture: /media/lwecke/B278E38678E347A5
#path_SdCardPicture: /media/lwecke/01D86604CD911790/SA_Wecke/raw_data/Frontal200FinalNew
#path_SdCardPicture: /media/lwecke/01D86604CD911790/SA_Wecke/raw_data/RightDataFinal200
#path_SdCardPicture: /media/lwecke/01D86604CD911790/SA_Wecke/raw_data/RightDataSetFinal80

path_for_loading_model_for_eval_only: /home/lwecke/PycharmProjects/flow_regime_recognition_CameraPosition/models/cnn_kroeger.h5
path_logs: /home/lwecke/PycharmProjects/flow_regime_recognition_CameraPosition/logs

#activate to create a pipeline. Functions will be executed in the listed sequence.
run_copyingDatasetFromUsbStick: false    #datapath must point to dest dir. source dir is path_SdCardPicture
run_preprocessing:              false
run_trimmingDataset:            false #ERROR timestamps are wrong. Deletes all inbetween periods. Nothing stays
run_labeling_balancing:         false #Balances Dataset and sets labels
run_tuner:                      false
run_training:                   true #works when set alone
run_evaluation_only:            false
run_saliencemapCreation:        false

preprocessing:
  filename_ExpermientTimestamps: ExpermientTimestamps.json
  filename_LabelTimestamps: LabelTimestamps.json
  picture_width: 56  #this value also is used for auto naming the preprocessed_images56 directory. Dont ONLY change hight. Allways use square values like 30x30
  picture_hight: 56
  no_classes: 3
  label_name: flow_regime
  file_type_picture: png
  autoplay_training: false # Depreciated. automaticly starts training after preprocessing.

callbacks: #count for tuning and training
  earlystop: true
  lr_schedule:
    enabled: false
    lr_max : 0.1
    lr_min : 0.0001
    lr_ramp_ep : 36
    lr_sus_ep : 40
    lr_decay : 0.3
training:
  comment: "Reduced Front"
  model_baseline: True #vanila LeNet5 without regularization and without dropout
  hp: #only work when model_baseline = False
    batch_size: 512
    dropout: 0.0
    regularization: 0.0
  no_epochs: 50
  loss: categorical_crossentropy
  learningrate: 0.001
  no_points_train_ratioInPercent: 0.6 #in percent
  no_points_val_ratioInPercent: 0.2 #training data = 1 - train - val
  dataset_test_no_repeats: 2

tuning:
  hp: #not in use
    batch_size: 50
    dropout: 0.2
    regularization: 0.001
  no_epochs: 50
  loss: categorical_crossentropy
  learningrate: 0.001
  no_points_train_ratioInPercent: 0.5 #choose small fraction of dataset for faster tuning.
  no_points_val_ratioInPercent: 0.3
  dataset_test_no_repeats: 2
globalValues:
  datashape: null
  labelshape: null
datashape: !!python/tuple  #Change if image resolution changes. Used by Hypermodel. Cant be used as parameter due to inheritance. Dirty workaround though.  Use PrettySaveLoader to load this yaml.
- 56
- 56
- 1
labelshape: 4 #dont change. Used by Hypermodel. Cant be used as parameter due to inheritance. Dirty workaround though.
