callbacks:
  earlystop: true
  lr_schedule:
    enabled: false
    lr_decay: 0.3
    lr_max: 0.1
    lr_min: 0.0001
    lr_ramp_ep: 36
    lr_sus_ep: 40
datashape: !!python/tuple
- 56
- 56
- 1
globalValues:
  datashape: null
  labelshape: null
input_bulktraining_image_root_path: "/home/lwecke/Datens\xE4tze/Test_datensatz_output/preprocessed_sorded_by_yaw"
input_output_labeling_path: "/home/lwecke/Datens\xE4tze/Test_datensatz_output/preprocessed_images56"
input_preprocessed_path: /media/lwecke/B278E38678E347A5/New_Test_dataset_2023-09-15
input_training_dataset_path: "/home/lwecke/Datens\xE4tze/Datensatz_v1_50p_3reg/Datensatz_v1_50p_3reg/preprocessed_images56"
labelshape: 3
output_bulktraining_path: "/home/lwecke/Datens\xE4tze/Test_datensatz_output/n_repeats"
output_preprocessed_path: "/home/lwecke/Datens\xE4tze/Test_datensatz_output/preprocessed_images56"
output_training_path: "/home/lwecke/Datens\xE4tze/Datensatz_v1_50p_3reg/Trainings_Outputs_dropout"
path_SdCardPicture: /media/lwecke/B278E38678E347A5/New_Test_dataset_2023-09-15
path_for_loading_model_for_eval_only: /home/lwecke/PycharmProjects/flow_regime_recognition_CameraPosition/models/cnn_kroeger.h5
path_logs: /home/lwecke/PycharmProjects/flow_regime_recognition_CameraPosition/logs
preprocessing:
  autoplay_training: false
  file_type_picture: png
  filename_ExpermientTimestamps: ExpermientTimestamps.json
  filename_LabelTimestamps: LabelTimestamps.json
  label_name: flow_regime
  no_classes: 3
  picture_hight: 56
  picture_width: 56
root_path_to_bulktraining_output: "/home/lwecke/Datens\xE4tze/Test_datensatz_output"
run_copyingDatasetFromUsbStick: false
run_evaluation_only: false
run_labeling_balancing: false
run_preprocessing: false
run_saliencemapCreation: false
run_training: false
run_training_for_subdir: true
run_trimmingDataset: false
run_tuner: false
training:
  dataset_test_no_repeats: 2
  hp:
    batch_size: 50
    dropout: 0.0
    regularization: 0.0
  learningrate: 0.001
  loss: categorical_crossentropy
  no_epochs: 90
  no_points_train_ratioInPercent: 0.6
  no_points_val_ratioInPercent: 0.2
tuning:
  dataset_test_no_repeats: 2
  hp:
    batch_size: 70
    dropout: 0.2
    regularization: 0.001
  learningrate: 0.001
  loss: categorical_crossentropy
  no_epochs: 1
  no_points_train_ratioInPercent: 0.5
  no_points_val_ratioInPercent: 0.3
